Update gen versions, including Herwig update and new build commands to handle Sherpa v3

diff --git a/install-herwig b/install-herwig
--- a/install-herwig
+++ b/install-herwig
@@ -2,11 +2,18 @@
 
 PREFIX=${PREFIX:-$PWD/local}
 BASE=$PWD
-THEPEG_VERSION=${THEPEG_VERSION:-2.2.3}
-HERWIG_VERSION=${HERWIG_VERSION:-7.2.3}
+THEPEG_VERSION=${THEPEG_VERSION:-2.3.0}
+HERWIG_VERSION=${HERWIG_VERSION:-7.3.0}
 
 # TODO: check for rsync libgsl-dev libboost-all-dev time gengetopt cython3 python3-six mercurial
-# TODO: check for lhapdf bin, fastjet,rivet,hepmc3,lhapdf libs
+# TODO: check for fastjet,rivet,hepmc3? All should be installed by rivet-bootstrap, so we shouldn't have to bother
+# TODO: check for lhapdf bin?
+
+## Check for LHAPDF
+if [[ -z "$(ls $PREFIX/lib/libLHAPDF.*)" ]]; then
+    echo "No libLHAPDF found in $PREFIX. Please install it either manually or by passing INSTALL_LHAPDF=1 to rivet-bootstrap. Aborting..." 1&>2
+    exit 2
+fi
 
 hg clone https://phab.hepforge.org/source/thepeghg -r $THEPEG_VERSION ThePEG
 cd ThePEG
diff --git a/install-pythia b/install-pythia
--- a/install-pythia
+++ b/install-pythia
@@ -2,7 +2,15 @@
 
 PREFIX=${PREFIX:-$PWD/local}
 BASE=$PWD
-PYTHIA_VERSION=${PYTHIA_VERSION:-8213}
+PYTHIA_VERSION=${PYTHIA_VERSION:-8313}
+
+# TODO: check for fastjet,rivet,hepmc3? All should be installed by rivet-bootstrap, so we shouldn't have to bother
+
+## Check for LHAPDF
+if [[ -z "$(ls $PREFIX/lib/libLHAPDF.*)" ]]; then
+    echo "No libLHAPDF found in $PREFIX. Please install it either manually or by passing INSTALL_LHAPDF=1 to rivet-bootstrap. Aborting..." 1&>2
+    exit 2
+fi
 
 wget --no-verbose https://pythia.org/download/pythia83/pythia${PYTHIA_VERSION}.tgz -O- | tar xz
 cd pythia*/
diff --git a/install-sherpa b/install-sherpa
--- a/install-sherpa
+++ b/install-sherpa
@@ -3,26 +3,57 @@
 PREFIX=${PREFIX:-$PWD/local}
 BASE=$PWD
 SHERPA_VERSION=${SHERPA_VERSION:-2.2.16}
+SHERPA_VERSION=${SHERPA_VERSION:-3.0.1}
 
 # TODO: check for rsync, scons and pypy3
 # TODO: update Sherpa to CMake build with v3
 # TODO: check for libtool, texinfo, texlive-metapost, feynmf, libsqlite3-dev, swig, openmpi-bin, libopenmpi-dev
 
+## Check for LHAPDF
+if [[ -z "$(ls $PREFIX/lib/libLHAPDF.*)" ]]; then
+    echo "No libLHAPDF found in $PREFIX. Please install it either manually or by passing INSTALL_LHAPDF=1 to rivet-bootstrap. Aborting..." 1&>2
+    exit 2
+fi
+
+## Install OpenLoops
 cd $PREFIX
 git clone https://gitlab.com/openloops/OpenLoops.git 
 cd OpenLoops
 ./scons
 ./openloops libinstall ppln ppln_ew pptt
 
-PATH=$PATH:/usr/lib64/openmpi/bin
+## Try to put OpenMPI in scope
+if [[ "${ENABLE_MPI:-0}" = 1 ]]; then
+    PATH=$PATH:/usr/lib64/openmpi/bin  #< TODO: make this (from Ubuntu Docker) more portable/robust... or leave to the user
+    export CC=mpicc
+    export CXX=mpic++
+else
+    NO_MPI=1  #< define variable to block MPI flag-substs below
+fi
+
+## Get Sherpa code
 cd $BASE
 git clone -b v${SHERPA_VERSION} https://gitlab.com/sherpa-team/sherpa.git
 cd sherpa
-autoreconf -fi
-./configure \
-  --prefix=$PREFIX \
-  --enable-{lhapdf,fastjet,hepmc3,openloops,rivet}=$PREFIX \
-  --enable-analysis --disable-pyext --enable-gzip --enable-mpi CC=mpicc CXX=mpic++
-make -j $(nproc --ignore=1) CXXFLAGS="-O2" AM_CXXFLAGS="-O2"
-make install
-mkdir $PREFIX/Sherpa && mv Examples /usr/local/Sherpa
+
+## Build and install, with different systems for v2.x and v3.x
+if [[ ${SHERPA_VERSION} =~ ^3\. ]]; then
+    ## New 3.x series
+    mkdir _BUILD
+    cmake -S . -B _BUILD -DCMAKE_INSTALL_PREFIX=$PREFIX \
+          -DRIVET_DIR=$PREFIX -DHEPMC3_DIR=$PREFIX \
+          ${NO_MPI:-"-DSHERPA_ENABLE_MPI=ON"}
+    cmake --build _BUILD  -j $(nproc --ignore=1)
+    cmake --install _BUILD
+else
+    ## Old 2.x series (remove at some point, when fully mainstream)
+    autoreconf -fi
+    ./configure \
+        --prefix=$PREFIX \
+        --enable-{lhapdf,fastjet,hepmc3,openloops,rivet}=$PREFIX \
+        --enable-analysis --disable-pyext --enable-gzip \
+        ${NO_MPI:-"--enable-mpi"}
+    make -j $(nproc --ignore=1) CXXFLAGS="-O2" AM_CXXFLAGS="-O2"
+    make install
+    mkdir -p $PREFIX/share/SHERPA-MC && cp -r Examples $PREFIX/share/SHERPA-MC/
+fi
