Added more error checking, and now SVN is only tried if not in developer mode.

diff --git a/rivet-bootstrap b/rivet-bootstrap
--- a/rivet-bootstrap
+++ b/rivet-bootstrap
@@ -1,5 +1,6 @@
 #! /usr/bin/env bash
 
+DEVELOPERMODE="no"
 
 ## Build and install to the PREFIX location
 PREFIX=$PWD/local
@@ -37,7 +38,7 @@ conf-mk-mkinst() {
     if test -d $1; then 
         (cd $1 && echo "./configure --prefix=$PREFIX" && \
             ./configure --prefix=$PREFIX --enable-shared && \
-            make && make install)
+            make && make install) || exit 2
     else
         echo "Couldn't find $1... exiting"
         exit 1
@@ -48,39 +49,40 @@ conf-mk-mkinst() {
 ##############################
 
 
-## Get Rivet and AGILe tarballs (for non-developers)
-AGILE_VERSION=1.0
-RIVET_VERSION=1.0
-AGILE_NAME=AGILe-$AGILE_VERSION
-RIVET_NAME=Rivet-$RIVET_VERSION
-if true; then
+## Get AGILe and Rivet either from released tarballs or SVN
+if test "$DEVELOPERMODE" != "yes"; then
+    ## USER MODE
+    ## Get Rivet and AGILe tarballs (for non-developers)
+    AGILE_VERSION=1.0
+    RIVET_VERSION=1.0
+    AGILE_NAME=AGILe-$AGILE_VERSION
+    RIVET_NAME=Rivet-$RIVET_VERSION
     AGILE_URL=http://www.hepforge.org/archive/agile/$AGILE_NAME.tar.gz
     echo "Getting $AGILE_URL"
     wget-untargz $AGILE_URL
-    ln -s $AGILE_NAME agile
+    ln -s $AGILE_NAME agile || exit 2
     RIVET_URL=http://www.hepforge.org/archive/rivet/$RIVET_NAME.tar.gz
     echo "Getting $RIVET_URL"
     wget-untargz $RIVET_URL
-    ln -s $RIVET_NAME rivet
-fi
-
-
-## If we've got SVN and there are no already-checked out versions
-## of AGILe and Rivet in this directory, then check out/update
-## the SVN head versions using the HTTP access method
-if test -x "`which svn 2> /dev/null`"; then
-    if test ! -e agile; then 
-        svn co http://svn.hepforge.org/agile/trunk agile
-        (cd agile && autoreconf -i)
-    fi
-
-    if test ! -e rivet; then 
-        svn co http://svn.hepforge.org/rivet/trunk rivet
-        (cd rivet && autoreconf -i) 
-    fi
+    ln -s $RIVET_NAME rivet || exit 2
 else
-    echo "Couldn't get AGILe and Rivet via svn" 1>&2
-    exit 1
+    ## DEVELOPER MODE
+    ## If we've got SVN and there are no already-checked out versions
+    ## of AGILe and Rivet in this directory, then check out/update
+    ## the SVN head versions using the HTTP access method
+    if test -x "`which svn 2> /dev/null`"; then
+        if test ! -e agile; then 
+            svn co http://svn.hepforge.org/agile/trunk agile || exit 2
+            (cd agile && autoreconf -i) || exit 2
+        fi
+        if test ! -e rivet; then 
+            svn co http://svn.hepforge.org/rivet/trunk rivet || exit 2
+            (cd rivet && autoreconf -i) || exit 2
+        fi
+    else
+        echo "Couldn't get AGILe and Rivet via svn" 1>&2
+        exit 1
+    fi
 fi
 
 
@@ -168,24 +170,24 @@ else
 
     ## Get LHAPDF
     LHAPDFNAME=lhapdf-$LHAPDF_VERSION
-    test -d $LHAPDFNAME || wget-untargz http://www.hepforge.org/archive/lhapdf/$LHAPDFNAME.tar.gz
-    conf-mk-mkinst $LHAPDFNAME
+    test -d $LHAPDFNAME || wget-untargz http://www.hepforge.org/archive/lhapdf/$LHAPDFNAME.tar.gz || exit 2
+    conf-mk-mkinst $LHAPDFNAME || exit 2
 
     ## Get HepMC
     HEPMCNAME=HepMC-$HEPMC_VERSION
-    test -d $HEPMCNAME || wget-untargz http://lcgapp.cern.ch/project/simu/HepMC/download/$HEPMCNAME.tar.gz
-    conf-mk-mkinst $HEPMCNAME
+    test -d $HEPMCNAME || wget-untargz http://lcgapp.cern.ch/project/simu/HepMC/download/$HEPMCNAME.tar.gz || exit 2
+    conf-mk-mkinst $HEPMCNAME || exit 2
 
     ## Get FastJet
     FASTJETNAME=fastjet-$FASTJET_VERSION
-    test -d $FASTJETNAME || wget-untargz http://www.lpthe.jussieu.fr/~salam/repository/software/fastjet/$FASTJETNAME.tar.gz
-    conf-mk-mkinst $FASTJETNAME
+    test -d $FASTJETNAME || wget-untargz http://www.lpthe.jussieu.fr/~salam/repository/software/fastjet/$FASTJETNAME.tar.gz || exit 2
+    conf-mk-mkinst $FASTJETNAME || exit 2
 
     ## Build and install AGILe
-    conf-mk-mkinst agile 
+    conf-mk-mkinst agile || exit 2
 
     ## Build and install Rivet
-    conf-mk-mkinst rivet
+    conf-mk-mkinst rivet || exit 2
     
     echo
     echo "All done. Now set some variables:"
